In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm

In [2]:
df = pd.read_csv(r"C:\Users\DELL\diabetes.csv")

In [3]:
df["Outcome"].value_counts(normalize=True)

Outcome
0    0.651042
1    0.348958
Name: proportion, dtype: float64

In [4]:
k = 5

In [5]:
X = df.drop(columns=["Outcome"])

In [6]:
y = df["Outcome"]

In [7]:
folds = np.random.choice(k, size=df.shape[0], replace=True)

In [8]:
X_train = X[folds!=0]
X_test = X[folds==0]
y_train = y[folds!=0]
y_test = y[folds==0]

In [9]:
clf = LogisticRegression()


In [10]:
clf.fit(X_train, y_train)

C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [11]:
y_pred = clf.predict(X_test)

In [12]:
print(y_pred)

[0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0
 1 0 0 0 1 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0
 0 0 1 0 0 0 1 1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1
 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0
 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0]


In [13]:
coeff = clf.coef_
coeff

array([[ 0.12232742,  0.03350742, -0.0122231 ,  0.00560695, -0.00206919,
         0.08459975,  0.79137121,  0.01231493]])

In [14]:
intercept = clf.intercept_
intercept

array([-7.9307741])

In [15]:
X.shape

(768, 8)

In [16]:
len(clf.coef_[0])

8

In [17]:
prob = clf.predict_proba(X_test)
prob

array([[0.56033212, 0.43966788],
       [0.27124646, 0.72875354],
       [0.45794061, 0.54205939],
       [0.71172631, 0.28827369],
       [0.94234206, 0.05765794],
       [0.84999871, 0.15000129],
       [0.86398529, 0.13601471],
       [0.0535736 , 0.9464264 ],
       [0.9534374 , 0.0465626 ],
       [0.20590341, 0.79409659],
       [0.60933773, 0.39066227],
       [0.98753522, 0.01246478],
       [0.97287439, 0.02712561],
       [0.85156205, 0.14843795],
       [0.99701654, 0.00298346],
       [0.91514464, 0.08485536],
       [0.34360589, 0.65639411],
       [0.87714035, 0.12285965],
       [0.32848475, 0.67151525],
       [0.79817842, 0.20182158],
       [0.90718713, 0.09281287],
       [0.97637361, 0.02362639],
       [0.84064166, 0.15935834],
       [0.77098149, 0.22901851],
       [0.38277521, 0.61722479],
       [0.64789679, 0.35210321],
       [0.74983845, 0.25016155],
       [0.98994433, 0.01005567],
       [0.38294826, 0.61705174],
       [0.54748344, 0.45251656],
       [0.

In [18]:
coef = pd.DataFrame({ "Features":X.columns, "Coefficient":coeff[0]})
coef

,Features,Coefficient
0,Pregnancies,0.122327
1,Glucose,0.033507
2,BloodPressure,-0.012223
3,SkinThickness,0.005607
4,Insulin,-0.002069
5,BMI,0.084600
6,DiabetesPedigreeFunction,0.791371
7,Age,0.012315


In [19]:
cf = confusion_matrix(y_test, y_pred)
cf

array([[102,   8],
       [ 18,  35]], dtype=int64)

In [20]:
acc = accuracy_score(y_test, y_pred)
acc

0.8404907975460123

In [21]:
recall = recall_score(y_test, y_pred)
recall

0.660377358490566

In [22]:
prec = precision_score(y_test, y_pred)
prec

0.813953488372093

In [23]:
f1 = f1_score(y_test, y_pred)
f1

0.7291666666666666

In [24]:
x_train_sm = sm.add_constant(X_train)
x_train_sm

,const,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,1.0,6,148,72,35,0,33.6,0.627,50
1,1.0,1,85,66,29,0,26.6,0.351,31
2,1.0,8,183,64,0,0,23.3,0.672,32
3,1.0,1,89,66,23,94,28.1,0.167,21
4,1.0,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...,...
761,1.0,9,170,74,31,0,44.0,0.403,43
762,1.0,9,89,62,0,0,22.5,0.142,33
763,1.0,10,101,76,48,180,32.9,0.171,63
764,1.0,2,122,70,27,0,36.8,0.340,27


In [25]:
logit_model = sm.Logit(y_train, x_train_sm)
logit_model

In [52]:
result = logit_model.fit()
result

Optimization terminated successfully.
         Current function value: 0.489057
         Iterations 6


In [54]:
print(result.summary2())

                             Results: Logit
Model:                  Logit              Pseudo R-squared:   0.248     
Dependent Variable:     Outcome            AIC:                609.7584  
Date:                   2026-05-01 11:45   BIC:                649.4055  
No. Observations:       605                Log-Likelihood:     -295.88   
Df Model:               8                  LL-Null:            -393.68   
Df Residuals:           596                LLR p-value:        5.4003e-38
Converged:              1.0000             Scale:              1.0000    
No. Iterations:         6.0000                                           
-------------------------------------------------------------------------
                          Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
-------------------------------------------------------------------------
const                    -7.8661   0.7736 -10.1685 0.0000 -9.3823 -6.3499
Pregnancies               0.1221   0.0355   3.4439 0.0006  0.0526  0

C:\ProgramData\anaconda3\lib\site-packages\statsmodels\iolib\summary2.py:579: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dat = dat.applymap(lambda x: _formatter(x, float_format))


In [56]:
#### EXAMS QUESTIONS

In [151]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [153]:
df = sns.load_dataset('titanic').dropna()

In [155]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True


In [157]:
df = pd.get_dummies(df)

In [159]:
df

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_female,sex_male,...,deck_C,deck_D,deck_E,deck_F,deck_G,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton,alive_no,alive_yes
1,1,1,38.0,1,0,71.2833,False,False,True,False,...,True,False,False,False,False,True,False,False,False,True
3,1,1,35.0,1,0,53.1000,False,False,True,False,...,True,False,False,False,False,False,False,True,False,True
6,0,1,54.0,0,0,51.8625,True,True,False,True,...,False,False,True,False,False,False,False,True,True,False
10,1,3,4.0,1,1,16.7000,False,False,True,False,...,False,False,False,False,True,False,False,True,False,True
11,1,1,58.0,0,0,26.5500,False,True,True,False,...,True,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,47.0,1,1,52.5542,False,False,True,False,...,False,True,False,False,False,False,False,True,False,True
872,0,1,33.0,0,0,5.0000,True,True,False,True,...,False,False,False,False,False,False,False,True,True,False
879,1,1,56.0,0,1,83.1583,False,False,True,False,...,True,False,False,False,False,True,False,False,False,True
887,1,1,19.0,0,0,30.0000,False,True,True,False,...,False,False,False,False,False,False,False,True,False,True


In [161]:
df["survived"].value_counts(normalize=True)

survived
1    0.675824
0    0.324176
Name: proportion, dtype: float64

In [163]:
X = df.drop(columns=["survived"])

In [165]:
y = df["survived"]

In [167]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [169]:
sc = StandardScaler()

In [171]:
X_train = sc.fit_transform(X_train)

In [173]:
X_test = sc.transform(X_test)

In [175]:
model = LogisticRegression()

In [177]:
model.fit(X_train, y_train)

LogisticRegression()

In [179]:
y_pred = model.predict(X_test)

In [183]:
print(confusion_matrix(y_test, y_pred))

[[13  0]
 [ 0 24]]


In [185]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        24

    accuracy                           1.00        37
   macro avg       1.00      1.00      1.00        37
weighted avg       1.00      1.00      1.00        37

